spring:
   application:
      name: edu-eureka
      
server:
   port: 8000
      
eureka:
   client:
      # 不注册当前应用
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka

        